addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.25")
addSbtPlugin("io.get-coursier"    % "sbt-coursier"             % "1.0.3")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt"             % "1.5.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"          % "2.3.7")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.5.1")
