addSbtPlugin("io.get-coursier"  % "sbt-coursier"              % "1.0.3")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"              % "1.5.1")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"           % "2.4.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.11")
